[project]
name = "retailco-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oliver Dee", email = "contact.eoliver@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
retailco-pipeline = "retailco_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
