[project]
name = "filmes-pipeline"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joao Victor Oliveira Silva", email = "oliveira.v@acad.ifma.edu.br" },
    { name = "Akilan", email = "@acad.ifma.edu.br" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "pandera>=0.33.1",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.3",
    "quarto-cli>=1.10.18",
    "requests>=2.34.2",
]
